---
title: "GenEst - Graphic User Interface"
author: "Juniper L. Simonis"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GenEst - 4. Graphic User Interface}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Overview

This document describes the codebase used to create the GenEst Graphic User Interface (GUI).

The Genest GUI is coded in HTML via external R packages (shiny, htmltools, shinyjs), as well as a number of internal functions to facilitate a simple, human-readable codebase underlying the app.

# User Interface

### UI Function Hierarchy

The GenEst User Interface is constructed using pages, panels, tabs, and widgets. The code is parsed into a series of hierarchical functions to facilitate readability and mobility of specific UI components.

* `GenEstUI(appType)`
  * `dataInputPanel()`
    * `dataInputSidebar()`
      * `dataInputWidget("SE")`
      * `dataInputWidget("CP")`
      * `dataInputWidget("SS")`
      * `dataInputWidget("DWP")`
      * `dataInputWidget("CO")`
    * `loadedDataPanel()`
      * `dataTabPanel("SE")`
      * `dataTabPanel("CP")`
      * `dataTabPanel("SS")`
      * `dataTabPanel("DWP")`
      * `dataTabPanel("CO")`
	* `analysisPanel()`
    * `GeneralInputsPanel()`
      * `GeneralInputsSidebar()`
        * `modelInputWidget("nsim")`
        * `modelInputWidget("CL")`
        * `modelInputWidget("sizeclassCol")`		
    * `SEPanel()`
      * `SESidebar()`
        * `modelInputWidget("obsCols_SE")`
        * `modelInputWidget("preds_SE")`
        * `modelInputWidget("kFixed")`
        * `modelRunWidget("SE")`
        * `modelOutputWidget("SE")`	   
      * `SEMainPanel()`	
        * `selectedDataPanel("SE")`
        * `modelOutputPanel("SEFigures")`
        * `modelOutputPanel("SEEstimates")`
        * `modelOutputPanel("SEModComparison")`
        * `modelOutputPanel("SEModSelection")`	  
    * `CPPanel()`
      * `CPSidebar()`
        * `modelInputWidget("ltp")`
        * `modelInputWidget("fta")`
        * `modelInputWidget("preds_CP")`
        * `modelInputWidget("dists")`
        * `modelRunWidget("CP")`
        * `modelOutputWidget("CP")`
      * `CPMainPanel()`
        * `selectedDataPanel("CP")`
        * `modelOutputPanel("CPFigures")`
        * `modelOutputPanel("CPEstimates")`
        * `modelOutputPanel("CPModComparison")`
        * `modelOutputPanel("CPModSelection")`	
	* `MPanel()`
      * `MSidebar()`
        * `modelInputWidget("kFill")`
        * `modelInputWidget("frac")`
        * `modelInputWidget("DWPCol")`
        * `modelInputWidget("dateFoundCol")`
        * `modelRunWidget("M")`
        * `modelOutputWidget("M")`
      * `MMainPanel()`	  
    * `gPanel()`
      * `gSidebar()`
        * `modelInputWidget("kFill_g")`
        * `modelInputWidget("gSearchInterval")`
        * `modelInputWidget("gSearchMax")`
        * `modelInputWidget("useSSinputs")`
        * `modelInputWidget("useSSdata")`
        * `modelRunWidget("g")`
        * `modelOutputWidget("g")`
      * `gMainPanel()`	
        * `selectedDataPanel("g")`
        * `modelOutputPanel("gFigures")`
        * `modelOutputPanel("gSummary")`	  
  * `helpPanel(type)`
    * `gettingStartedPanel()`
      * `gettingStartedContent()`
    * `downloadsPanel()`
      * `dataDownloadsWidget("RP")`
      * `dataDownloadsWidget("RPbat")`
      * `dataDownloadsWidget("cleared")`
      * `dataDownloadsWidget("powerTower")`
      * `dataDownloadsWidget("PV")`
      * `dataDownloadsWidget("trough")`
      * `dataDownloadsWidget("mock")`
      * `dataDownloadsWidget("mock2")`
    * `aboutPanel()`
      * `aboutContent()`
        * `GenEstAuthors()`
        * `GenEstGUIauthors()`
        * `GenEstLicense()`
        * `GenEstAcknowledgements()`
        * `GenEstLogos()`
    * `disclaimersPanel(appType)`
      * `disclaimerContent(appType)`
        * `disclaimerUSGS()`
        * `disclaimerWEST(appType)`		
		
### UI Widgets

* `dataInputWidget(dataType)`
* `modelInputWidget(inType)`		
* `modelRunWidget(modType)`
* `modelOutputWidget(modType)`	   
* `dataDownloadsWidget(set)`
* `modelSelectionWidget(modType)`	  
* `kFixedWidget()`
		
### UI Panels

* `dataTabPanel(dataType)`
* `selectedDataPanel(modType)`
* `modelOutputPanel(outType)`

### UI Content

* `gettingStartedContent()`
* `aboutContent()`
* `GenEstAuthors()`
* `GenEstGUIAuthors()`
* `GenEstLicense()`
* `GenEstAcknowledgements()`
* `GenEstLogos()`
* `disclaimersContent(appType)`
* `disclaimerUSGS()`
* `disclaimerWEST(appType)`


* `navbar()`

# Execution 

`runGenEst()`